---
version: 2
sources:
- name: "AIRLINES_AIRLINES"
  database: "AIRLINES"
  schema: "AIRLINES"
  tables:
  - name: "a1h"
    description: "Details of aircraft models, including their range and codes, supporting\
      \ fleet management and planning decisions."
    identifier: "dummy"
    config:
      tags:
      - "pipeline:p2"
    quoting:
      identifier: true
    columns:
    - name: "AIRPORT_CODE"
      description: "Unique code assigned to each airport, used for identification\
        \ in travel and logistics."
      dataType:
        type: "String"
    - name: "AIRPORT_NAME"
      description: "Official name of the airport as recognized by aviation authorities."
      dataType:
        type: "String"
    - name: "CITY"
      description: "City where the airport is located or primarily serves."
      dataType:
        type: "String"
    - name: "COORDINATES"
      description: "Geographical latitude and longitude of the airport location."
      dataType:
        type: "String"
    - name: "TIMEZONE"
      description: "Time zone in which the airport operates, affecting flight schedules\
        \ and operations."
      dataType:
        type: "String"
    type: "table"
  - name: "snow_alias"
    description: "Comprehensive information on airports, supporting identification\
      \ and location of airports by name, code, city, and timezone."
    identifier: "AIRPORTS_DATA"
    config:
      tags:
      - "pipeline:p3"
    quoting:
      identifier: true
    columns:
    - name: "AIRPORT_CODE"
      description: "Unique code assigned to each airport, used for identification\
        \ in travel and logistics."
      dataType:
        type: "String"
    - name: "AIRPORT_NAME"
      description: "Official name of the airport as recognized by aviation authorities."
      dataType:
        type: "String"
    - name: "CITY"
      description: "City where the airport is located or primarily serves."
      dataType:
        type: "String"
    - name: "COORDINATES"
      description: "Geographical latitude and longitude of the airport location."
      dataType:
        type: "String"
    - name: "TIMEZONE"
      description: "Time zone in which the airport operates, affecting flight schedules\
        \ and operations."
      dataType:
        type: "String"
    type: "table"
